const mongoose = require('mongoose');

const ai1data = new mongoose.Schema({
    Date_Time: Date,
    AI1CH1_Scale_Min: String,
    AI1CH1_Scale_Max: String,
    AI1CH1_Raw_Min: String,
    AI1CH1_Raw_Max: String,
    AI1CH1_High_High_Set_Value: String,
    AI1CH1_High_Set_Value: String,
    AI1CH1_Low_Set_Value: String,
    AI1CH1_Low_Low_Set_Value: String,
    AI1CH1_Timer_Set_Time: String,
    AI1CH2_Scale_Min: String,
    AI1CH2_Scale_Max: String,
    AI1CH2_Raw_Min: String,
    AI1CH2_Raw_Max: String,
    AI1CH2_High_High_Set_Value: String,
    AI1CH2_High_Set_Value: String,
    AI1CH2_Low_Set_Value: String,
    AI1CH2_Low_Low_Set_Value: String,
    AI1CH2_Timer_Set_Time: String,
    AI1CH3_Scale_Min: String,
    AI1CH3_Scale_Max: String,
    AI1CH3_Raw_Min: String,
    AI1CH3_Raw_Max: String,
    AI1CH3_High_High_Set_Value: String,
    AI1CH3_High_Set_Value: String,
    AI1CH3_Low_Set_Value: String,
    AI1CH3_Low_Low_Set_Value: String,
    AI1CH3_Timer_Set_Time: String,
    AI1CH4_Scale_Min: String,
    AI1CH4_Scale_Max: String,
    AI1CH4_Raw_Min: String,
    AI1CH4_Raw_Max: String,
    AI1CH4_High_High_Set_Value: String,
    AI1CH4_High_Set_Value: String,
    AI1CH4_Low_Set_Value: String,
    AI1CH4_Low_Low_Set_Value: String,
    AI1CH4_Timer_Set_Time: String,
    AI1CH5_Scale_Min: String,
    AI1CH5_Scale_Max: String,
    AI1CH5_Raw_Min: String,
    AI1CH5_Raw_Max: String,
    AI1CH5_High_High_Set_Value: String,
    AI1CH5_High_Set_Value: String,
    AI1CH5_Low_Set_Value: String,
    AI1CH5_Low_Low_Set_Value: String,
    AI1CH5_Timer_Set_Time: String,
    AI1CH6_Scale_Min: String,
    AI1CH6_Scale_Max: String,
    AI1CH6_Raw_Min: String,
    AI1CH6_Raw_Max: String,
    AI1CH6_High_High_Set_Value: String,
    AI1CH6_High_Set_Value: String,
    AI1CH6_Low_Set_Value: String,
    AI1CH6_Low_Low_Set_Value: String,
    AI1CH6_Timer_Set_Time: String,
    AI1CH7_Scale_Min: String,
    AI1CH7_Scale_Max: String,
    AI1CH7_Raw_Min: String,
    AI1CH7_Raw_Max: String,
    AI1CH7_High_High_Set_Value: String,
    AI1CH7_High_Set_Value: String,
    AI1CH7_Low_Set_Value: String,
    AI1CH7_Low_Low_Set_Value: String,
    AI1CH7_Timer_Set_Time: String,
    AI1CH8_Scale_Min: String,
    AI1CH8_Scale_Max: String,
    AI1CH8_Raw_Min: String,
    AI1CH8_Raw_Max: String,
    AI1CH8_High_High_Set_Value: String,
    AI1CH8_High_Set_Value: String,
    AI1CH8_Low_Set_Value: String,
    AI1CH8_Low_Low_Set_Value: String,
    AI1CH8_Timer_Set_Time: String,
});

const Ai1data = mongoose.model('ai1data', ai1data);

module.exports = Ai1data;