const mongoose = require('mongoose');

const PtLineDashboard = new mongoose.Schema({
  Date_Time: Date,
  Time: String,
  HWPUMPSTATLBL: String,
  HWPUMPMOTLBL: String,
  HWTANKLVLLBL: String,
  HWCIRPRSRLBL: String,
  HWTEMPLBL: String,
  HWSOFTWATERLBL: String,
  PDPUMPSTATLBL: String,
  PDPUMPMOTLBL: String,
  PDTANKLVLLBL: String,
  PDCIRPRSRLBL: String,
  PDTEMPLBL: String,
  PDSOFTWATERLBL: String,
  DPUMPSTATLBL: String,
  DPUMPMOTLBL: String,
  DTANKLVLLBL: String,
  DCIRPRSRLBL: String,
  DTEMPLBL: String,
  DSOFTWATERLBL: String,
  WR1PUMPSTATLBL: String,
  WR1PUMPMOTLBL: String,
  WR1TANKLVLLBL: String,
  WR1CIRPRSRLBL: String,
  WR1TEMPLBL: String,
  WR1SOFTWATERLBL: String,
  WR2PUMPSTATLBL: String,
  WR2PUMPMOTLBL: String,
  WR2TANKLVLLBL: String,
  WR2CIRPRSRLBL: String,
  WR2TEMPLBL: String,
  WR2SOFTWATERLBL: String,
  WR3PUMPSTATLBL: String,
  WR3PUMPMOTLBL: String,
  WR3TANKLVLLBL: String,
  WR3CIRPRSRLBL: String,
  WR3TEMPLBL: String,
  WR3SOFTWATERLBL: String,
  WR4PUMPSTATLBL: String,
  WR4PUMPMOTLBL: String,
  WR4TANKLVLLBL: String,
  WR4CIRPRSRLBL: String,
  WR4TEMPLBL: String,
  WR4SOFTWATERLBL: String,
  DMPUMPSTATLBL: String,
  DMPUMPMOTLBL: String,
  DMTANKLVLLBL: String,
  DMCIRPRSRLBL: String,
  DMTEMPLBL: String,
  DMSOFTWATERLBL: String,
  OXPUMPSTATLBL: String,
  OXPUMPMOTLBL: String,
  OXTANKLVLLBL: String,
  OXCIRPRSRLBL: String,
  OXTEMPLBL: String,
  OXSOFTWATERLBL: String,
  FDWPUMPSTATLBL: String,
  FDWPUMPMOTLBL: String,
  FDWTANKLVLLBL: String,
  FDWCIRPRSRLBL: String,
  FDWTEMPLBL: String,
  FDWSOFTWATERLBL: String
});

const PtLine = mongoose.model('Reportdatatabel', PtLineDashboard);

module.exports = PtLine;
